### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by jepler** [jepler/pi-gen#1]
Checklist of things to do before more widely publicizing the image this builds:
 - [x] Enable SPI overlay 
 - [x] install ntpd, ensure systemd-timesyncd is turned off
 - [x] any non-warranty-voiding speed tweaks
 - [ ] a proper apt repository for the linuxcnc and kernel images
 - [ ] package mesaflash
 - [ ] package a 2.8ish linuxcnc

Would be nice
 - [ ] pi3 kernel
 - [ ] linuxcnc build deps preinstalled?
 - [x] enable the right opengl
 - [ ] inhibit or disable screensaver/screen locking by default

**Comment by jepler** [comment]
The second iteration image is (sha256sum)
9ecc85d997ad2cba65fbb0ea6a780a00ce3b75012cb00892ce77528b9bbb33fa  https://media.unpythonic.net/image_2020-01-08-linuxcnc-pi4-full.zip

**Comment by samcoinc** [comment]
Couple things..   
-The screen shouldn't go to sleep on a machine control.  (I think)  But I haven't figured out how to change that.
-Force_turbo=1 doesn't void the warranty bit.  (and I think it still throttles down when too hot)
https://www.raspberrypi.org/documentation/configuration/config-txt/overclocking.md

**Comment by jepler** [comment]
Hm, himblick uses a program "caffeinate" as a wrapper to disable screensaver.  Not sure how to apply that to linuxcnc.  Perhaps it's not the right technique anyway.  https://www.enricozini.org/blog/2019/himblick/himblick-media-player/ https://manpages.debian.org/buster/caffeine/caffeinate.1.en.html
